<h2>Înregistrare</h2>
<h3>Completare informații</h3>
<?php if($page['afiseaza_formular']): ?>
<!-- Start of signup table -->
<form action="auth/signup"  method="post">
<table class="full">
	<tr>
		<th>Nume</th>
			<td><input type="text" value="<?=$_POST['user_first_name']?>" name="user_first_name" /></td>
	</tr>
	<tr>
		<th>Prenume</th>
			<td><input type="text" value="<?=$_POST['user_last_name']?>" name="user_last_name" /></td>
	</tr>
	<tr>
		<th>Username</th>
			<td><input type="text" value="<?=$_POST['user_name']?>" name="user_name" /></td>
	</tr>
	<tr>
		<th>User type</th>
		<td><select name="user_type">
		<option <?php if($_POST['user_type']=='1') echo 'selected="selected"' ?> value="1">Client</option>
		<option <?php if($_POST['user_type']=='2') echo 'selected="selected"' ?> value="2">Analist</option>
		<option <?php if($_POST['user_type']=='3') echo 'selected="selected"' ?> value="3">Proiectant</option>
		<option <?php if($_POST['user_type']=='4') echo 'selected="selected"' ?> value="4">Programator</option>
		<option <?php if($_POST['user_type']=='5') echo 'selected="selected"' ?> value="5">Tester</option>
		</select></td>
	</tr>
	<tr>
		<th>Parola</th>
			<td><input value="<?=$_POST['user_password']?>" name="user_password" type="password" /></td>
	</tr>
	<tr>
		<th>Rescrie parola</th>
			<td><input value="<?=$_POST['test_password']?>" name="test_password" type="password" /></td>
	</tr>
	<tr>
		<th>CNP</td>
			<td><input type="text" value="<?=$_POST['user_cnp']?>" name="user_cnp" size="13" maxlength="13"/></td>
	</tr>
	<tr>
		<th>E-mail</th>
			<td><input type="text" value="<?=$_POST['user_email']?>" name="user_email" /></td>
	</tr>
	<tr>
		<th>Telefon</th>
			<td><input type="text" value="<?=$_POST['user_phone']?>" name="user_phone" size="10" maxlength="10" /></td>
	</tr>
	<tr>
		<th>Adresa</th>
			<td><textarea name="user_address" cols="20" rows="3"><?php
		if ($_POST) echo $_POST['user_address'];
		else echo "Completeaza adresa..."; ?></textarea></td>
	</tr>
	<tr>
		<th>Website</th>
			<td><input type="text" value="<?=$_POST['user_website']?>" name="user_website" /></td>
	</tr>
	<tr>
		<th>Verificare anti-spam</th>
		<script type="text/javascript">var RecaptchaOptions = { theme : "clean" };</script>		
		<td><?=$page['recaptcha']?></td>
	</tr>
	<tr align="center">
		<td colspan="2"><input type="submit" value="Inregistreaza-te!" /></td>
	</tr>
	<tr>
		<td colspan="2"><a href="auth/index" >Ai deja cont? Conecteaza-te!</a></td>
	</tr>
	<?php  if (isset($page['error'])) echo '
	<tr>
		<td colspan="2" width="610"><b style="color:red"> Eroare: '.$page['error'].'</b></td>
	</tr>
	'; ?>
	<tr>
		<td colspan="2"><a href="auth/reactiv">Daca doriti sa va reactivati un cont sters click aici.</a></td>
	</tr>
</table>
</form>

<!-- End of signup table-->

<?php endif; ?>
<?php if(!isset($page['afiseaza_formular'])): ?>
<?php
			echo $page['content'];
?>
<?php endif ?>