<h2>Echipa</h2>
<br/><br/>
<table style="width: 100%; text-align: center">
<tr>
	<td width="33%">
		<img src="template/img/alex.jpg" width="150">
	</td>
	<td width="33%">
		Alexandru Georoceanu<br/>
		Grupa 243
	</td>
	<td> </td>
</tr>
<tr>
	<td width="33%"> </td>
	<td  width="33%">
		Madalina Popescu<br/>
		Grupa 243
	</td>
	<td style="text-align: left">
		<img src="template/img/mady.jpg" width="150">
	</td>
</tr>
<tr>
	<td width="33%">
		<img src="template/img/danny.jpg" width="150">
	</td>
	<td>
		Daniel Arhire<br/>
		Grupa 243
	</td>
	<td> </td>
</tr>
</table>
<br/><br/>