<?php if($page['not_allowed'] == true): ?>
	Nu ai acces la aceasta pagina.
<?php else: if($page['done'] == true): ?>
	<?php redirect("http://nexuspro.info/index") ?>
<?php else: if($page['fara_id'] == true): ?>
	Adresa este gresita, nu ai specificat nici un id.
<?php else: if($page['nu_exista'] == true): ?>
	Anuntul cautat nu exista.
<?php else: ?>
	<h2>Editeaza anunt</h2>
	<?php if($page['incomplet'] == true): ?>
		<br/>Trebuie completate toate campurile.
	<?php endif; ?>
	<br/><br/>
	<form method="post" action="statice/editeaza_anunt/id/<?=$_GET['id']?>">
		Titlu: <br/>
		<input type="text" name="titlu" size="64" value="<?=$_POST['titlu']?>"><br/>
		Text: <br/>
		<textarea name="text" cols="48" rows="4"><?=$_POST['text']?></textarea>
		<br/><br/>
		<input type="submit" value="Editeaza">	
	</form>
<?php endif;endif;endif;endif; ?>