<?php if($page['not_logged_in']):?>
	<center> 
		<?=$page['not_logged_in']?> <br/>
		<a href="auth/index">Login</a> sau <a href="auth/signup">Inregistreaza-te</a>
	</center>
<?php else : if($page['err']): ?>
	<?=$page['err']?><br/>
	<a href="forum/index">inapoi la index</a>
<?php else : if($page['not_modif']): ?>
	<?=$page['not_modif']?><br/>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a>
<?php else : if($page['nu_exista']): ?>
	<?=$page['nu_exista']?><br/>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a>
<?php else : if($page['done']): ?>
		<?php redirect('forum/thread/cat_id/'.$_GET[cat_id].'/thr_id/'.$_GET['thr_id'].''); ?>
<?php else: ?>
	<h3>Editeaza post</h3>
	<?php if($page['fara_titlu']): ?>
		<br/><?=$page['fara_titlu']?>
	<?php endif; ?>
	<br/><br/>
	<form action="forum/editeaza_post/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>/post_id/<?=$_GET['post_id']?>" method="post">
		Titlu: <br/><input type="text" name="titlu" value="<?=$page['nume']?>" size="64"><br>	
		Post:<br/> 
		<textarea name="cont" rows="4" cols="48"><?=$page['cont']?></textarea><br/><br/>
		<input type="submit" value="Modifica">
	</form><br/>
	<h3>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a></h3>

	<?php endif; ?>
<?php endif;endif;endif;endif; ?>
