<?php if($page['not_logged_in']):?>
	<?=$page['not_logged_in']?> <br/>
	<a href="auth/index">Login</a> sau <a href="auth/signup">Inregistreaza-te</a>
<?php else : if($page['not_allowed']): ?>
	<?=$page['not_allowed']?><br/>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a>
<?php else: if($page['self'] == true): ?>
	Administratorul nu isi poate dezactiva singur contul. Contacteaza alt administrator pentru ajutor.<br/>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a>
<?php else : if($page['err']): ?>
	<?=$page['err']?><br/>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a>
<?php else: if($page['pr_desf'] == true): ?>
	Userul are proiecte active in desfasurare si nu poate fi sters momentan.<br/>
	<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
	<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
	<a href="/forum/index">inapoi la index</a>
<?php else :?>
	<?php if($page['done']): ?>
		<?=$page['done']?><br/>
		<?php redirect('forum/thread/cat_id/'.$_GET[cat_id].'/thr_id/'.$_GET['thr_id'].''); ?>
	<?php else: ?>
			<h3>Sterge user</h3>
			<br/><br/>
			<form action="/forum/sterge_toate/thr_id/<?=$_GET['thr_id']?>/cat_id/<?=$_GET['cat_id']?>/user_id/<?=$_GET['user_id']?>" method="post">
			<input type="checkbox" name="sterge"> Sterg toate posturile si inchid contul userului <?=$page['nume']?>?<br/><br/>
			<input type="submit" value="Sterge">
			</form>
			<br/><h3>
			<a href="forum/thread/cat_id/<?=$_GET['cat_id']?>/thr_id/<?=$_GET['thr_id']?>">Inapoi la thread</a>, 
			<a href="/forum/categorie/id/<?=$_GET['cat_id']?>">la categorie</a> sau 
			<a href="/forum/index">inapoi la index</a></h3>
	<?php endif; ?>					
<? endif;endif;endif;endif;endif; ?>