<?php if($page['not_logged_in']):?>
		<?=$page['not_logged_in']?> <br/>
		<a href="auth/index">Login</a> sau <a href="auth/signup">Inregistreaza-te</a>
<?php else : if($page['user']): ?>
	Nu ai selectat nici un user.<br/>
	<a href="forum/index">Inapoi la index</a>
<?php else : if($page['pag_gresita']): ?>
	<?=$page['pag_gresita']?> <br/>
	<a href="forum/viewposts/user_id/<?=$_GET['user_id']?>/pag/1">Mergi la prima pagina</a>
<?php else : if($page['no_posts']): ?>
	<?=$page['no_posts']?> <br/>	
	Inapoi la <a href="ucp/profil/username/<?=$page['username']?>">profil</a><br/><br/>
<?php else: ?>
	<a href="forum/index">Index</a><br/>
	Inapoi la <a href="ucp/profil/username/<?=$page['username']?>">profil</a><br/><br/>
	<br/>
	
	<?php foreach($page['content'] as $c): ?>
		<div style="background-color: #FFF3A3; padding: 5px; border: 1px solid #FFDE00; width: 90%; margin: 3px;">
			<table style="width: 100%; border: 1px solid #FFF;">
				<tr>
					<td colspan="4">
						<a href="forum/categorie/id/<?=$c['cat_id']?>"><?=$c['cat_name']?></a> --- <a href="forum/thread/cat_id/<?=$c['cat_id']?>/thr_id/<?=$c['thr_id']?>"><?=$c['thr_name']?></a>
						<?php if($c['status'] == 0): ?>
							- <span style="color: red">INCHIS</span>
						<?php endif; ?>
					</td>
				</tr>
				<?php if($page['perm'] == 'admin'): ?>
					
					<tr style="font-size: 12px;text-align: right;">
						<td style="width: 25%"> </td>
						<td style="width: 25%">
							<a href="forum/editeaza_post/cat_id/<?=$c['cat_id']?>/thr_id/<?=$c['thr_id']?>/post_id/<?=$c['post_id']?>">editeaza</a>
						</td>
						<td style="width: 25%">
							<a href="forum/sterge_toate/cat_id/<?=$c['cat_id']?>/thr_id/<?=$c['thr_id']?>/user_id/<?=$c['user_id']?>">sterge tot</a>
						</td>
						<td style="width: 25%">
							<a href="forum/sterge_post/cat_id/<?=$c['cat_id']?>/thr_id/<?=$c['thr_id']?>/post_id/<?=$c['post_id']?>">sterge</a>
						</td>					
					</tr>
				
				<?php else: if($c['user_m'] == true && $c['user_id'] == $_SESSION['user_id']): ?>
					<tr style="font-size: 12px;text-align: right;">
						<td style="width: 25%"> </td>
						<td style="width: 25%"> </td>
						<td style="width: 25%"> </td>
						<td style="width: 25%">
							<a href="forum/editeaza_post/cat_id/<?=$c['cat_id']?>/thr_id/<?=$c['thr_id']?>/post_id/<?=$c['post_id']?>">editeaza</a>
						</td>					
					</tr>
				<?php endif;endif;?>
				<tr>
					<td colspan="4">
						Titlu: <?=$c['titlu']?>
					</td>
				</tr>
				<tr>
					<td colspan="2"> 
						Autor: <a href="ucp/profil/username/<?=$c['user']?>"><?=$c['user']?></a>
					</td>
					<td colspan="2" style="text-align: right;"> 
						Data: <?=$c['data_c']?>
					</td>
				</tr>
				<tr>
					<td colspan="4" style="border-top: 1px solid #FFF">
						<?=$c['text']?>
					</td>
				</tr>
			</table>
		</div>
	 <?php endforeach; ?> 
	 <br/><br/>
		<div style="width: 100%; text-align: center">
			<div style="width: 50%">
				<?php for($i = 1; $i <= $page['nr_pag']; $i++):?>
						-
						<?php if($i == $_GET['pag']): ?>
							<?=$i?>
						<?php else: ?>
							<a href="forum/viewposts/user_id/<?=$_GET['user_id']?>/pag/<?=$i?>">
								<?=$i?>
							</a>
						<?php endif; ?>
						-
					
				<? endfor; ?>
			</div>
		</div>
<?php endif;endif;endif;endif;?>